title: "Geomática y Topografía"
author: "Fabio Regolf Ariño"
description: "Diario de un estudiante de Ingeniería Geomática y Topografía. Experiencias en prácticas, divulgación y reflexiones."
theme: minima
feed: false
