title: "Geomática y Topografía" 
author: "Fabio Regolf Ariño<br>Estudiante de Ingeniería Geomática y Topografía<br>Precolegiado Nº PR00205"
description: "Diario de un estudiante de Ingeniería Geomática y Topografía. Experiencias en prácticas, divulgación y reflexiones."
theme: minima
