title: "Geomática y Topografía" 
author: "Fabio Regolf Ariño
Estudiante de Ingeniería Geomática y Topografía
Precolegiado Nº PR00205"
description: "Diario de un estudiante de Ingeniería Geomática y Topografía. Experiencias en prácticas, divulgación y reflexiones."
theme: minima
